export const READ = 'INTEGRATIONS_READ';
export const READ_ALL = 'INTEGRATIONS_READ_ALL';
export const CREATE = 'INTEGRATIONS_CREATE';
export const UPDATE = 'INTEGRATIONS_UPDATE';
export const UPDATE_CALLBACKS = 'INTEGRATIONS_UPDATE_CALLBACKS';
export const DELETE = 'INTEGRATIONS_DELETE';
export const READ_CREDENTIALS = 'INTEGRATIONS_READ_CREDENTIALS';
